version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - DB_NAME=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:13.7-alpine
    container_name: postgres-order
    ports:
      - "6541:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
volumes:
  postgres-data: